blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='blog-home'),
    path('home/',views.home,name='home'),
    path('login/',views.login),
    path('about/',views.about,name="blog-about"),
    path('registration/',views.registration,name="blog-regis"),
    path('newusersavedata/',views.newusersavedata,name="blog-newuserentry"),
	path('checkuserdata/',views.checkuserdata),
	path('saveblogpost/',views.saveblogpost),
	path('showmypost/',views.showmypost),
	path('showotherpost/',views.showotherpost),
	path('newpost/',views.newpost),
	path('signup/',views.signup),
	path('forgotpassword/',views.forgotpassword),
	path('logout/',views.logout),
	]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
	title=models.CharField(max_length=100)
	content=models.TextField()
	date_posted=models.DateTimeField(default=timezone.now)
	author=models.ForeignKey(User,on_delete=models.CASCADE)
class newuserentry(models.Model):
	name=models.CharField(max_length=50)
	email=models.CharField(max_length=100)
	phone=models.CharField(max_length=15)
	password=models.CharField(max_length=50)
	class Meta:
		db_table="newuserentry"	
class blogpost(models.Model):
	author=models.CharField(max_length=100)
	title=models.CharField(max_length=100)
	content=models.TextField()
	date_posted=models.DateTimeField(default=timezone.now)
	class Meta:
		db_table="blogpost"
	def __str__(self):
		return self.title

	

blog/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from blog.models import newuserentry
from django.http import HttpResponse
from blog.models import blogpost
from datetime import datetime
from django.core.mail import send_mail,EmailMessage
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
dt,at={},{}
lt=[]
un,k='',""
u=''
a=''
posts=[{'title':'Welcome to my awesome blog app'
,'author':'Arpit Agarwal',
'content':'This is a blog app which was made by me.I used django framework of python to developed it.Share your views for this app.Hope you like it.',
'date_posted':'22 March,2019'}]
def signup(request):
	if request.method=='POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			'''n=request.POST.get("username")
			e=request.POST.get("email")
			ph=request.POST.get("phone")
			p=request.POST.get("password1")
			p2=request.POST.get("password2")
			nwet=newuserentry(name=n,email=e,phone=ph,password=p)
			nwet.save()
			return render(request,'blog/redirectlogin.html',{})'''
			form.save()
			messages.success(request,'Account created succesfully')
			return render(request,'blog/redirectlogin.html',{})
			
			
	else:
		form=UserCreationForm()
	return render(request,'blog/signuptest.html',{'form':form})
def home(request):
	context={'posts':posts}
	return render(request,'blog/home.html',context)
def about(request):
	return render(request,'blog/about.html',{'title':'about'})
def login(request):
	return render(request,'blog/login.html',{})	
def registration(request):
	form=UserCreationForm()
	return render(request,'blog/signuptest.html',{'form':form})	
@csrf_exempt	
def newusersavedata(request):
	if request.method=="POST":
		n=request.POST.get("username")
		e=request.POST.get("email")
		ph=request.POST.get("phone")
		p=request.POST.get("password")
		nwet=newuserentry(name=n,email=e,phone=ph,password=p)
		nwet.save()
		return render(request,'blog/redirectlogin.html',{})
@csrf_exempt
def checkuserdata(request):
	if request.method=="POST":
		form=AuthenticationForm(data=request.POST)
		u=request.POST.get('username')
		p=request.POST.get('password')
		objects=newuserentry.objects.all()
		lt=[{'uname':u,'upass':p}]
	
		at=dt.copy()
		
		context={
		'lt':lt
		}
		if form.is_valid():
			return render(request,'blog/postform.html',context)
		else:
			form=AuthenticationForm()
			return HttpResponse("<h1>No such data</h1>")		

		'''u=request.POST.get('username')
		p=request.POST.get('password')
		objects=newuserentry.objects.all()
		lt=[{'uname':u,'upass':p}]
	
		at=dt.copy()
		
		context={
		'lt':lt
		}
		
		for x in objects:
			if(u==x.name and p==x.password):
				name_1=u
				return render(request,'blog/postform.html',context)
				
				return 

		else:
			return HttpResponse("<h1>No such data</h1>")'''		
				
@csrf_exempt	
def saveblogpost(request):
	if request.method=="POST":
		a=request.POST.get("author")
		k=a
		t=request.POST.get("title")
		c=request.POST.get("content")
		d=datetime.now()
		formatedDate = d.strftime("%Y-%m-%d %H:%M:%S")
		if(a=='' or t=='' or c=='' or d==''):
			return HttpResponse("<h1>Please create the valid post")
		else:
			bp=blogpost(author=a,title=t,content=c,date_posted=formatedDate)
			bp.save()
			obj=blogpost.objects.filter(author=a)
			if obj.exists():
				res=""
				mypost=[]
				for x in obj:
					au=res+x.author
					ti=res+x.title
					co=res+x.content
					da=res+str(x.date_posted)
					myp={'title':ti,'author':au,'content':co,'date_posted':da}
					for i in range(0,1):
						mypost.insert(i,myp)	
				contexttwo={'mypost':mypost}
				return render(request,'blog/showblogpage.html',contexttwo)
			else:
				return HttpResponse("<H1>You have zero post to show....</H1>")
			'''return render(request,'blog/showuserpost.html',{})'''
@csrf_exempt
def showmypost(request):
	if request.method=="POST":
		k=request.POST.get("authorone")
	obj=blogpost.objects.filter(author=k)
	if obj.exists():
		res=""
		mypost=[]
		for x in obj:
			au=res+x.author
			ti=res+x.title
			co=res+x.content
			da=res+str(x.date_posted)
			myp={'title':ti,'author':au,'content':co,'date_posted':da}
			for i in range(0,1):
				mypost.insert(i,myp)	
		contexttwo={'mypost':mypost}
		return render(request,'blog/showblogpage.html',contexttwo)
	else:
		return HttpResponse("<H1>You have zero post to show....</H1>")	
@csrf_exempt
def showotherpost(request):
	if request.method=='POST':
		amy=request.POST.get('authorfive')
		obj=blogpost.objects.all()
	res=""
	mypost=[]
	for x in obj:
		au=res+x.author
		ti=res+x.title
		co=res+x.content
		da=res+str(x.date_posted)
		myp={'title':ti,'author':au,'content':co,'date_posted':da,'uname':amy}
		for i in range(0,1):
			mypost.insert(i,myp)	
	contextthree={'mypost':mypost}
	return render(request,'blog/mybasetwo.html',contextthree)	
@csrf_exempt
def newpost(request):
	if request.method=="POST":
		aut=request.POST.get("authorfour")
	lt=[{'uname':aut}]
	contextfour={
	'lt':lt
	}	
	return render(request,'blog/postform.html',contextfour)
def forgotpassword(request):
	'''ltp=['arpitagarwal916.aa@gmail.com']
	res=send_mail("Hello arpit","hi it work",'arpitagarwal990@gmail.com',ltp,fail_silently=True)
	'''
	return HttpResponse("<h1>This feature will be added soon...")	
def logout(request):
	return render(request,"blog/logout.html",{})	

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
	<p>This is the mini blogging web application design to post blog and seen others blog.This blogging application is based on Django framework.</p>
	<br>
	<p>It updated version will be available soon...</p><br>
	<h1>Thank You.</h1>
{% endblock content %}	

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
	{% if title %}
	<title>Django blog-{{title}}</title>
	{% else %}
	<title>Django blog</title>
	{% endif %}
	
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="/login/">Login</a>
          <a class="nav-item nav-link" href="/registration/">Register</a>
        </div>
      </div>
    </div>
  </nav>
</header>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>	
	
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/blogpostpage.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% for i in lt %}
		<h1>WELCOME {{ i.uname }} </h1>
		<p> {{ i.upass }}</p>
	{% endfor %}	

</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
	{% for post in posts%}
	<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
	{% endfor %}
{% endblock content %}	

blog/templates/blog/login.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Log in | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">





    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    

<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" login"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">WELCOME TO ONLINEBLOGINGAPP</a></h1>

        </div>
        
        
    </div>
    <!-- END Header -->
    
    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        
        




<div id="content-main">



<form action="/checkuserdata/" method="post" id="login-form"><input type="hidden" name="csrfmiddlewaretoken" value="W2oeymEwsWbSWRedfVGi5zmEiosSuupCdhiOJCNycckn0fxZRrls4s5wgp3OiZmE">
  <div class="form-row">
    
    <label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus required id="id_username">
  </div>
  <div class="form-row">
    
    <label class="required" for="id_password">Password:</label> <input type="password" name="password" required id="id_password">
    <input type="hidden" name="next" value="/admin/">
  </div>
  
  
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in"><br>
    <a href="/registration/">New user?Registred</a>
   <br>
    <br><a href="/forgotpassword/">Forgot Password ?</a>
  </div>
</form>

</div>

        
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

blog/templates/blog/logout.html
{% extends "blog/base.html" %}
{% block content %}
	<h1>Thank you for log in...</h1>
	<br>
	<a href="/home/">Back to dashboard</a><br>
	
{% endblock content %}	

blog/templates/blog/mybaseone.html
{% load static %}
<!DOCTYPE html>
<html>
<head >
	 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
	<!--{% if title %}
	<title>Django blog-{{title}}</title>
	{% else %}
	<title>Django blog</title>
	{% endif %}-->
   {% for post in mypost %}
          {% if forloop.first %}
          <title>Welcome {{post.author}} </title>
          {% endif %}
        {% endfor %}
	
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
    {% for post in mypost %}
          {% if forloop.first %}
      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Welcome {{post.author}}</a>

      <form method="POST" action="/newpost/">
      <input type="hidden" name="authorfour" value={{post.author}}>
      </form>
      {% endif %}
        {% endfor %}
          
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog-home' %}">Log out</a>
          <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
        <div>
          
      <!--<a  class="nav-item nav-link" href="/newpost/" >New Post</a>-->
        {% for post in mypost %}
          {% if forloop.first %}
        <form method="POST" action="/newpost/">
        <button  name="authorfour" class="default" value={{post.author}}>New Post</button><br>

        </form>
        {% endif %}
        {% endfor %}
         
        </div>
        <div>
          {% for post in mypost %}
            {% if forloop.first %}
          <form method="POST" action="/showotherpost/">
         <button  name="authorfive" class="default" value={{post.author}}>Show Other Post</button>
        </form>
        {% endif %}
        {% endfor %}
        </div>
          
        </div>
    
          
         
        </div>
      </div>
    </div>
  </nav>
</header>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% block content %}
        {% for post in mypost %}
  

 
  
  <article class="media content-section">

  <div class="media-body">

    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>

      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
  {% endfor %}
      {% endblock %}
    </div>
    <div class="col-md-4">
      
    </div>
  </div>
</main>	
	
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/mybasetwo.html
{% load static %}
<!DOCTYPE html>
<html>
<head >
	 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
	<!--{% if title %}
	<title>Django blog-{{title}}</title>
	{% else %}
	<title>Django blog</title>
	{% endif %}-->
   {% for post in mypost %}
          {% if forloop.first %}
          <title>Welcome {{post.uname}} </title>
          {% endif %}
        {% endfor %}
	
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
    {% for post in mypost %}
          {% if forloop.first %}
      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Welcome {{post.uname}}</a>

      <form method="POST" action="/newpost/">
      <input type="hidden" name="authorfour" value={{post.uname}}>
      </form>
      {% endif %}
        {% endfor %}
          
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog-home' %}">Dashboard</a>
          <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
        <div>
          
      <!--<a  class="nav-item nav-link" href="/newpost/" >New Post</a>-->
        {% for post in mypost %}
          {% if forloop.first %}
        <form method="POST" action="/newpost/">
        <button  name="authorfour" class="nav-item nav-link" value={{post.uname}}>New Post</button>

        </form>
        {% endif %}
        {% endfor %}
         
        </div>
        <!--<div>
          {% for post in mypost %}
          <form method="POST" action="/showotherpost/">
         <button  name="authorfive" class="nav-item nav-link" value={{post.author}}>Show Other Post</button>
        </form>
        
        {% endfor %}
        </div>-->
          
        </div>
    
          
         
        </div>
      </div>
    </div>
  </nav>
</header>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% block content %}
        {% for post in mypost %}
  

 
  
  <article class="media content-section">

  <div class="media-body">

    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>

      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
  {% endfor %}
      {% endblock %}
    </div>
    <div class="col-md-4">
      
    </div>
  </div>
</main>	
	
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/redirectlogin.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<H1>Record saved Sucessfully</H1>
<a href="/home/">Back to login</a>
</body>
</html>

blog/templates/blog/registration.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Log in | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">





    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    

<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" login"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">WELCOME TO ONLINEBLOGINGAPP</a></h1>

        </div>
        
        
    </div>
    <!-- END Header -->
    
    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        
        




<div id="content-main">



<form action="/newusersavedata/" method="post" id="login-form"><input type="hidden" name="csrfmiddlewaretoken" value="W2oeymEwsWbSWRedfVGi5zmEiosSuupCdhiOJCNycckn0fxZRrls4s5wgp3OiZmE">
  
  <div class="form-row">
    
    <label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus required id="id_username">
  </div>
  <div class="form-row">
    
    <label class="required" for="id_email">Email:</label> <input type="email" name="email" autofocus required id="id_email">
  </div>
  <div class="form-row">
    
    <label class="required" for="id_password">Password:</label> <input type="password" name="password" required id="id_password">
    <input type="hidden" name="next" value="/admin/">
  </div>
 <div class="form-row">
    
    <label class="required" for="id_phone">PhoneNo:</label> <input type="text" name="phone" autofocus required id="id_phone">
  </div>
  
  
  
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in"><br>
    
  </div>
</form>

</div>

        
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

blog/templates/blog/showblogpage.html
{% extends "blog/mybaseone.html" %}
{% block content %}
  <div>
     {% for post in mypost %}
      <form method="POST" action="/newpost/">
        <input type="hidden" name="authorfour" value={{ post.author}}>
      </form>
      {% endfor %}
    </div>

  {% for post in mypost %}
  

 
  
  <article class="media content-section">

  <div class="media-body">

    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>

      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
  {% endfor %}
{% endblock content %}  

blog/templates/blog/showotherblogpage.html
{% extends "blog/mybaseone.html" %}
{% block content %}
  {% for post in mypost %}
  <article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
  {% endfor %}
{% endblock content %}  

blog/templates/blog/showuserpost.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	
</head>
<body>
<h1> POST SUCCESSFULL</h1>
</body>
</html>

blog/templates/blog/signuptest.html
{% extends "blog/base.html" %}
{% block content %}
  
  <h1>Sign Up</h1>

  <form class="site-form" action="/signup/" method="POST">
  {% csrf_token %}
    {{ form }}
    <br><label>Email:</label><input type="email" name="email">
    <label>Phone:</label><input type="text" name="phone">
    <br><input type="submit" name="submit" value="signup">
    
  </form>
 
{% endblock content %}  